// src/queries/boardQueries.ts
export const getBoardListsQuery = `
  SELECT
    TB_BOARD.BOARD_ID AS BOARD_ID,
    TB_BOARD.BOARD_TITLE AS BOARD_TITLE,
    TB_BOARD.BOARD_CONTENT AS BOARD_CONTENT,
    TB_BOARD.BOARD_HIT AS BOARD_HIT,
    TB_BOARD.CREATED_DATE AS CREATED_DATE,
    TB_BOARD.MODIFIED_DATE AS MODIFIED_DATE,
    TB_BOARD.USER_ID AS USER_ID,
    TB_BOARD.USER_NM AS USER_NM,
    TB_BOARD.USER_EMAIL AS USER_EMAIL,
    TB_BOARD.B_MAIN_CATE_ID AS B_MAIN_CATE_ID,
    TB_BOARD.B_MID_CATE_ID AS B_MID_CATE_ID
  FROM TB_BOARD
  ORDER BY TB_BOARD.CREATED_DATE
`;

export const getSpecificBoardListsQuery = `
  SELECT
    TB_BOARD.BOARD_ID AS BOARD_ID,
    TB_BOARD.BOARD_TITLE AS BOARD_TITLE,
    TB_BOARD.BOARD_CONTENT AS BOARD_CONTENT,
    TB_BOARD.BOARD_HIT AS BOARD_HIT,
    TB_BOARD.CREATED_DATE AS CREATED_DATE,
    TB_BOARD.MODIFIED_DATE AS MODIFIED_DATE,
    TB_BOARD.USER_ID AS USER_ID,
    TB_BOARD.USER_NM AS USER_NM,
    TB_BOARD.USER_EMAIL AS USER_EMAIL,
    TB_BOARD.B_MAIN_CATE_ID AS B_MAIN_CATE_ID,
    TB_BOARD.B_MID_CATE_ID AS B_MID_CATE_ID
  FROM TB_BOARD
  WHERE BOARD_ID = $1
`;
